version: "3.9"
services:
  db:
    build: ./db
    env_file:
      - .env
    ports:
      - "5432:5432"
  web:
    image: hekata.pro:5000/edtech_backend:0.1.8
    env_file:
      - .env
    depends_on:
      - db
